services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5434/Employee
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
  #  app-2:
  #    build:
  #      context: .
  #    ports:
  #      - "8001:8001"
  #    environment:
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Employee
  #      SPRING_DATASOURCE_USERNAME: postgres
  #      SPRING_DATASOURCE_PASSWORD: postgres
  #    depends_on:
  #      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: Employee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5434"